url: 
baseurl: 

# Site settings
title: Comunicación en crisis
email: elixabete.perez@deusto.es
description: "Jornadas 'Comunicación en crisis'"


# Team names, titles and social links
people:
- name: Pablo Rey Mazón
  pic: pablo-rey
  position: Numeroteca
  social:
    - title: twitter
      url: https://twitter.com/numeroteca
    - title: link
      url: http://montera34.com/
    - title: link
      url: http://numeroteca.org/
    - title: github
      url: https://github.com/numeroteca/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/deustokom
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket 
#    url: http://bitbucket.org/jekyll
  # - title: youtube
  #   url: https://www.youtube.com/playlist?list=PLUDmL1Ad-O82FJU0pLl9iBhFaxtwYI_zL
  - title: github
    url: http://github.com/deustokom/

# Postal address (add as many lines as necessary)
address:
  - line: Mundaiz 50
  - line: 20012 Donostia

# Build settings
markdown: kramdown